-- Pais
INSERT INTO PAIS (codigo_pais, pais) VALUES ('COL', 'Colombia');
INSERT INTO PAIS (codigo_pais, pais) VALUES ('USA', 'Estados Unidos');
INSERT INTO PAIS (codigo_pais, pais) VALUES ('MEX', 'México');

-- Caracter Empresa
INSERT INTO CARACTER_EMPRESA VALUES (1);
INSERT INTO CARACTER_EMPRESA VALUES (2);
INSERT INTO CARACTER_EMPRESA VALUES (3);

-- Grupo Empresa
INSERT INTO GRUPO_EMPRESA VALUES (1, 'Tecnología');
INSERT INTO GRUPO_EMPRESA VALUES (2, 'Comercio');
INSERT INTO GRUPO_EMPRESA VALUES (3, 'Manufactura');

-- Moneda
INSERT INTO MONEDA VALUES (1, 'Peso Colombiano');
INSERT INTO MONEDA VALUES (2, 'Dólar Estadounidense');
INSERT INTO MONEDA VALUES (3, 'Peso Mexicano');

-- Banco
INSERT INTO BANCO
VALUES (101, 'Bancolombia', 12.5, 15000, 'COL');

INSERT INTO BANCO
VALUES (102, 'Banco de Bogotá', 11.8, 12000, 'COL');

INSERT INTO BANCO
VALUES (103, 'Bank of America', 8.3, 30, 'USA');

-- Empresa
INSERT INTO EMPRESA
VALUES (201, 'TecnoSoft', 1, 1);

INSERT INTO EMPRESA
VALUES (202, 'Comercial ABC', 2, 2);

INSERT INTO EMPRESA
VALUES (203, 'Industrias XYZ', 3, 3);

-- Moneda Pais
INSERT INTO MONEDA_PAIS
VALUES (1, 'COL', 1, 0);

INSERT INTO MONEDA_PAIS
VALUES (2, 'USA', 1, 0);

INSERT INTO MONEDA_PAIS
VALUES (3, 'MEX', 1, 0);

INSERT INTO MONEDA_PAIS
VALUES (2, 'COL', 4200, 2.3);

INSERT INTO MONEDA_PAIS
VALUES (3, 'COL', 225, 1.5);

-- Credito
INSERT INTO CREDITO
VALUES (1001, 5, 101, 201);

INSERT INTO CREDITO
VALUES (1002, 8, 102, 202);

INSERT INTO CREDITO
VALUES (1003, 10, 103, 203);

-- Credito Modena
INSERT INTO CREDITO_MONEDA
VALUES (1001, 1, 50000000);

INSERT INTO CREDITO_MONEDA
VALUES (1002, 1, 80000000);

INSERT INTO CREDITO_MONEDA
VALUES (1003, 2, 250000);
